Repository joeltankam/checkif.js, pull requests merged in 2018-10, with the labels that each got.

#16 Refactor 'all'
  README.md
  index.js
  src/all.js
  test/all.test.js
Labels: improvement

#18 Update 'all' checker
  README.md
  src/all.js
  test/all.test.js
Labels: bug, improvement

#13 Adds support for any.
  README.md
  src/any.js
  test/any.test.js
Labels: duplicate, enhancement

#34 Move 'is' to folder instead of single file
  src/all.js
  src/any.js
  src/is/index.js
  src/is/types.js
  test/is/types.test.js
Labels: improvement
